### ISSUE TITLE
TypeError: Cannot read property 'logger' of undefined

### ISSUE THREAD

**Issue by W4G1** [deepstreamIO/deepstream.io-storage-rethinkdb#27]
I can't seem to get this plugin to work with even the simplest configuration. Any ideas?

Snippet to reproduce:
```javascript
const { Deepstream } = require('@deepstream/server')
const RethinkDBStorage = require('@deepstream/storage-rethinkdb')

const server = new Deepstream()

server.set('storage', new RethinkDBStorage.Connector({
  host: 'localhost',
  port: 28015
}))
  
server.start()
```

Output:
```shell
D:\project\node_modules\@deepstream\storage-rethinkdb\src\connector.ts:38
  private logger = this.services.logger.getNameSpace('RETHINDB')
                                 ^
TypeError: Cannot read property 'logger' of undefined
    at new Connector (D:\project\node_modules\@deepstream\storage-rethinkdb\src\connector.ts:38:34)
    at Object.<anonymous> (D:\project\deepstream.js:6:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by yasserf** [comment]
whats ur config file?

**Comment by W4G1** [comment]
I'm using the default config, the one that can be found here: https://github.com/deepstreamIO/deepstream.io/blob/master/conf/config.yml

No modifications made whatsoever.

I'm using Node v14.15.4 if that makes any difference.

**Comment by jaime-ez** [comment]
Hi, try doing it through the server options, I believe the example on this readme is outdated:
```
const server = new Deepstream({
  storage: {
    name: 'rethinkdb',
    options: {
     host: 'localhost',
     port: 28015
   }
 },
})
```

**Comment by jaime-ez** [comment]
Can confirm that was the issue, readme updated
