### ISSUE TITLE
Error when field is undefined

### ISSUE THREAD

**Issue by WolframHempel** [deepstreamIO/deepstream.io-storage-rethinkdb#5]
Will have to do more research, but the driver now seems to throw an error when a field is undefined

```
RqlDriverError: Object field 'brand' may not be undefined
    at new RqlDriverError (/home/ec2-user/deepstreamhub-tests/ds-server/node_modules/rethinkdb/errors.js:14:13)
    at new MakeObject (/home/ec2-user/deepstreamhub-tests/ds-server/node_modules/rethinkdb/ast.js:1522:15)
    at Function.<anonymous> (/home/ec2-user/deepstreamhub-tests/ds-server/node_modules/rethinkdb/ast.js:3901:12)
    at Function.expr (/home/ec2-user/deepstreamhub-tests/ds-server/node_modules/rethinkdb/util.js:39:16)
    at new MakeObject (/home/ec2-user/deepstreamhub-tests/ds-server/node_modules/rethinkdb/ast.js:1524:37)
    at Function.<anonymous> (/home/ec2-user/deepstreamhub-tests/ds-server/node_modules/rethinkdb/ast.js:3901:12)
    at Function.expr (/home/ec2-user/deepstreamhub-tests/ds-server/node_modules/rethinkdb/util.js:39:16)
    at Table.<anonymous> (/home/ec2-user/deepstreamhub-tests/ds-server/node_modules/rethinkdb/ast.js:1053:45)
    at Table.insert (/home/ec2-user/deepstreamhub-tests/ds-server/node_modules/rethinkdb/util.js:60:16)
    at Connector._insert (/home/ec2-user/deepstreamhub-tests/ds-server/node_modules/deepstream.io-storage-rethinkdb/src/connector.js:177:4)
    at Connector.set (/home/ec2-user/deepstreamhub-tests/ds-server/node_modules/deepstream.io-storage-rethinkdb/src/connector.js:73:3)
    at RecordTransition._next (/home/ec2-user/deepstreamhub-tests/ds-server/node_modules/deepstream.io/src/record/record-transition.js:224:25)
    at RecordTransition._onRecord (/home/ec2-user/deepstreamhub-tests/ds-server/node_modules/deepstream.io/src/record/record-transition.js:171:8)
    at RecordRequest._onCacheResponse (/home/ec2-user/deepstreamhub-tests/ds-server/node_modules/deepstream.io/src/record/record-request.js:55:8)
    at LocalCache.get (/home/ec2-user/deepstreamhub-tests/ds-server/node_modules/deepstream.io/src/default-plugins/local-cache.js:12:2)
    at new RecordRequest (/home/ec2-user/deepstreamhub-tests/ds-server/node_modules/deepstream.io/src/record/record-request.js:32:22)

```

**Comment by yasserf** [comment]
https://github.com/deepstreamIO/deepstream.io/issues/216

**Comment by ronag** [comment]
This is fixed with 1.0.1?

**Comment by yasserf** [comment]
I don't think so, this issue was raised before 1.0 when we inversed data structure.

**Comment by ronag** [comment]
@yasserf: Given that we now have a `parse(stringify)` before reaching rethinkdb I don't think this scenario is possible?

**Comment by yasserf** [comment]
Oo, good point! I'll close this for now then and open it if it ever reproduces
